# Generated by Django 4.2.3 on 2023-07-25 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.BigIntegerField(verbose_name='Идентификатор транзакции')),
                ('asset', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('pay_url', models.CharField(max_length=1024, verbose_name='Ссылка на оплату')),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('PAID', 'paid'), ('EXPIRED', 'expired')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(verbose_name='Дата создания оплаты')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
