# Generated by Django 4.2.3 on 2023-09-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_invoice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
