# Generated by Django 4.2.3 on 2023-09-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_invoice_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='asset',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания оплаты'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор транзакции'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pay_url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
