# Generated by Django 4.2.3 on 2023-09-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_invoice_asset_alter_invoice_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование услуги')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Наименование услуги')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Наименование услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена ($)')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.service', verbose_name='Наименование услуги'),
        ),
    ]
