# Generated by Django 4.2.3 on 2023-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара ')),
                ('link', models.CharField(max_length=2048, verbose_name='Ссылка на товар')),
                ('quantity', models.IntegerField(verbose_name='Количество товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена товара')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='visits',
            options={'verbose_name': 'Последний визит', 'verbose_name_plural': 'Последние визиты'},
        ),
        migrations.AddField(
            model_name='account',
            name='purchases',
            field=models.ManyToManyField(null=True, to='accounts.purchase', verbose_name='Покупки'),
        ),
    ]
