# Generated by Django 4.2.3 on 2023-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_purchase_alter_visits_options_account_purchases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='tracking_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Трек номер'),
        ),
        migrations.AlterField(
            model_name='account',
            name='purchases',
            field=models.ManyToManyField(to='accounts.purchase', verbose_name='Покупки'),
        ),
    ]
