# Generated by Django 4.2.3 on 2023-07-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountdata_account_country_account_addresses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdata',
            options={'verbose_name': 'Доставочный адрес', 'verbose_name_plural': 'Доставочные адреса'},
        ),
    ]
