# Generated by Django 4.2.3 on 2023-07-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accountdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('BUYOUT', 'buyout'), ('FORWARDING', 'forwarding'), ('ACCEPTANCE', 'acceptance')], default='ACCEPTANCE', max_length=255, verbose_name='Текущий статус:'),
        ),
    ]
