# Generated by Django 4.2.3 on 2023-07-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_purchase_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Доступна')),
            ],
            options={
                'verbose_name': 'Доставочная опция',
                'verbose_name_plural': 'Доставочные опции',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='options',
            field=models.ManyToManyField(to='accounts.purchasedeliveryoption', verbose_name='Доступные опции доставки'),
        ),
    ]
