# Generated by Django 4.2.3 on 2023-07-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_purchasedeliveryoption_purchase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='options',
            field=models.ManyToManyField(blank=True, to='accounts.purchasedeliveryoption', verbose_name='Доступные опции доставки'),
        ),
    ]
