# Generated by Django 4.2.3 on 2023-07-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_purchase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sur_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
