# Generated by Django 4.2.3 on 2023-07-29 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_sur_name_accountdata_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountdata'),
        ),
    ]
