# Generated by Django 4.2.3 on 2023-07-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_telegramsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_notifications', models.BooleanField(default=True)),
                ('notify_news', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TelegramSettings',
        ),
        migrations.AddField(
            model_name='account',
            name='telegram_notify',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='accounts.notifysettings'),
            preserve_default=False,
        ),
    ]
