# Generated by Django 4.2.3 on 2023-07-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_accountnotifysettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountnotifysettings',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки пользовательских уведомлений'},
        ),
    ]
