# Generated by Django 4.2.3 on 2023-07-29 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_notifysettings_delete_telegramsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_notifications', models.BooleanField(default=True)),
                ('notify_news', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='telegram_notify',
        ),
        migrations.DeleteModel(
            name='NotifySettings',
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
