# Generated by Django 4.2.3 on 2023-07-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_accountnotifysettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedeliveryoption',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='purchasedeliveryoption',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
    ]
