# Generated by Django 4.2.3 on 2023-07-29 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_telegramsettings_remove_account_telegram_notify_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramSettings',
            new_name='EmailNotifySetting',
        ),
        migrations.RenameField(
            model_name='emailnotifysetting',
            old_name='notify_news',
            new_name='is_email_status',
        ),
        migrations.RenameField(
            model_name='emailnotifysetting',
            old_name='status_notifications',
            new_name='is_news',
        ),
        migrations.CreateModel(
            name='TelegramNotifySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_message_status', models.BooleanField(default=True)),
                ('is_news', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
