# Generated by Django 4.2.3 on 2023-07-29 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_notifysetting_remove_telegramnotifysetting_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifysetting',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
