# Generated by Django 4.2.3 on 2023-07-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_buyoutcategory_buyout'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_method',
            field=models.CharField(max_length=255, null=True, verbose_name='Метод доставки'),
        ),
    ]
