# Generated by Django 4.2.3 on 2023-07-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_notifysetting_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotifySetting',
            new_name='AccountNotifySettings',
        ),
    ]
