# Generated by Django 4.2.3 on 2023-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_purchase_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_deliveried',
            field=models.BooleanField(default=False, verbose_name='Доставлена'),
        ),
    ]
