# Generated by Django 4.2.3 on 2023-09-09 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_accountdata_first_name_accountdata_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created'], 'verbose_name': 'покупку', 'verbose_name_plural': 'покупки'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountdata', verbose_name='Куда нужно переслать'),
        ),
    ]
