# Generated by Django 4.2.3 on 2023-09-09 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0026_alter_purchase_options_alter_purchase_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_warehouse_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Идентификатор склада для доставки'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_warehouse_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип склада для доставки'),
        ),
    ]
