# Generated by Django 4.2.3 on 2023-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_purchase_delivery_warehouse_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_ready_pay',
            field=models.BooleanField(default=False, verbose_name='Готова к оплате'),
        ),
    ]
