# Generated by Django 4.2.3 on 2023-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_purchase_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор транзакции'),
        ),
    ]
