# Generated by Django 4.2.5 on 2023-10-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_purchase_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_track_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Последний трек номер'),
        ),
        migrations.AddField(
            model_name='account',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_status',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Статус покупки'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_status_last_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='remarks',
            field=models.CharField(blank=True, null=True, verbose_name='Примечания'),
        ),
    ]
