# Generated by Django 4.2.3 on 2023-10-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_account_last_track_number_account_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_status',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_status_last_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
