# Generated by Django 4.2.3 on 2023-10-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_account_user_status_account_user_status_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_track_number',
        ),
        migrations.AddField(
            model_name='purchase',
            name='track_after_sent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='трек после отправления'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечания'),
        ),
    ]
