# Generated by Django 4.2.3 on 2023-07-23 14:27

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Улица')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('state', models.CharField(max_length=255, verbose_name='Штат')),
                ('zip', models.CharField(max_length=255, verbose_name='Почтовый индекс')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('opened', models.DateTimeField(default=datetime.datetime.now, verbose_name='Склад открыт')),
                ('closed', models.DateTimeField(default=main.models.now_plus_month, verbose_name='Склад будет закрыт')),
            ],
        ),
    ]
