# Generated by Django 4.2.3 on 2023-07-31 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountWarehouse',
            fields=[
                ('warehouse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.warehouse')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады пользователей',
            },
            bases=('main.warehouse',),
        ),
    ]
