# Generated by Django 4.2.3 on 2023-08-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Улица')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('state', models.CharField(max_length=255, verbose_name='Штат')),
                ('zip', models.CharField(max_length=255, verbose_name='Почтовый индекс')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады пользователей',
            },
        ),
    ]
