# Generated by Django 4.2.3 on 2023-08-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0003_accountwarehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Имя магазина')),
                ('quantity', models.BigIntegerField(default=0, verbose_name='Количество заказов на адрес')),
                ('image', models.ImageField(max_length=2048, upload_to='', verbose_name='Путь до фото')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Магазин склада',
                'verbose_name_plural': 'Магазины склада',
            },
        ),
    ]
