# Generated by Django 4.2.3 on 2023-10-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_warehouseshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountwarehouse',
            name='is_opened',
            field=models.BooleanField(default=False, verbose_name='Открыт'),
        ),
        migrations.AddField(
            model_name='accountwarehouse',
            name='opened_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата открытия склада'),
        ),
    ]
